development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://h:p5fd1c89b02acb12ea6a85ed3a881cf297d6930524a4ba0c7f5766499cf013822@ec2-63-32-250-106.eu-west-1.compute.amazonaws.com:13739
  # channel_prefix: scoreboard_production
